// Service Worker for WealthPulse
// Pre-caches all static assets for offline-first usage

/// <reference lib="webworker" />

import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';

declare let self: ServiceWorkerGlobalScope;

clientsClaim();
self.skipWaiting();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// Navigation fallback — serve index.html for all navigation requests
registerRoute(
  new NavigationRoute(
    new NetworkFirst({
      cacheName: 'navigate',
    })
  )
);

// Cache exchange rate API calls with network-first (1 hour TTL)
registerRoute(
  ({ url }) => url.hostname.includes('open.er-api.com') || url.hostname.includes('frankfurter.app'),
  new NetworkFirst({
    cacheName: 'exchange-rates',
    networkTimeoutSeconds: 8,
  })
);
